---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: memelord-hirmus-database
  labels:
    cnpg.io/reload: "true"
spec:
  data:
    username: memelord-hirmus
  fields:
    - fieldName: password
      length: "32"
      encoding: hex
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: memelord-hirmus-database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 1Gi
    storageClass: postgres
  affinity:
    podAntiAffinityType: required
    nodeSelector:
      codemowers.io/lvm-ubuntu-vg: enterprise-ssd
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: "512MB"
      effective_cache_size: "2GB"
  managed:
    roles:
    - name: memelord-hirmus
      ensure: present
      login: true
      passwordSecret:
        name: memelord-hirmus-database
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memelord-hirmus
spec:
  name: memelord-hirmus
  owner: memelord-hirmus
  cluster:
    name: memelord-hirmus-database

